### ISSUE TITLE
Code wrong?

### ISSUE THREAD

**Issue by ouyangjiacs** [tedlasai/ae-video-platform#2]
exposure_saliency.py
line40:current_map = np.reshape(self.salient_map[j-1][ind],(total_n_pixs))
is it wrong?

(when I run the Saliency_map algorithm,scene4, error:

Saliency_map
Exception in Tkinter callback
Traceback (most recent call last):
  File "/data/env/anaconda3/envs/mmm/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/data/env/anaconda3/envs/mmm/lib/python3.9/tkinter/__init__.py", line 3948, in __call__
    self.__callback(self.__value, *args)
  File "/data/work/AE/ae-video-platform-main/browser_builder.py", line 218, in setAutoExposure
    self.eV, self.eV_original, self.weighted_means, self.hists = exposures.pipeline()
  File "/data/work/AE/ae-video-platform-main/exposure_saliency.py", line 40, in pipeline
    current_map = np.reshape(self.salient_map[j-1][ind],(total_n_pixs))
  File "<__array_function__ internals>", line 200, in reshape
  File "/data/env/anaconda3/envs/mmm/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/data/env/anaconda3/envs/mmm/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 18816 into shape (470400,)
Saliency_map
Exception in Tkinter callback
Traceback (most recent call last):
  File "/data/env/anaconda3/envs/mmm/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/data/work/AE/ae-video-platform-main/browser_builder.py", line 179, in <lambda>
    command=lambda: command_function(para))
  File "/data/work/AE/ae-video-platform-main/button_functions.py", line 81, in resetValues
    self.setAutoExposure()
  File "/data/work/AE/ae-video-platform-main/browser_builder.py", line 218, in setAutoExposure
    self.eV, self.eV_original, self.weighted_means, self.hists = exposures.pipeline()
  File "/data/work/AE/ae-video-platform-main/exposure_saliency.py", line 40, in pipeline
    current_map = np.reshape(self.salient_map[j-1][ind],(total_n_pixs))
  File "<__array_function__ internals>", line 200, in reshape
  File "/data/env/anaconda3/envs/mmm/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/data/env/anaconda3/envs/mmm/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 18816 into shape (470400,)

)

**Comment by tedlasai** [comment]
Hi, does this only happen for Scene 4?

**Comment by ouyangjiacs** [comment]
I just run this code in Scene 4, but I notice that the shape of data in Scene1 is same to the shape of data in Scene4

**Comment by tedlasai** [comment]
Does the saliency method work for you in Scene 1?

**Comment by ouyangjiacs** [comment]
I haven't tested in Scene1, just have a loot at the shape of date which is same to Scene4.

**Comment by tedlasai** [comment]
Sure, we will look into this issue. Please give us a few days.

**Comment by ouyangjiacs** [comment]
thank you very much.
looking forward to your reply.

**Comment by AliciaY-720** [comment]
Hi, Jia. Thanks for your feedback. We uploaded a downsized version of the RAW image npy files in the folder '' RAW_npy_downsized_100_40_224_336". We also updated the readme file. Please use the downsized version as the input images.

**Comment by ouyangjiacs** [comment]
okay, thank you very much for your feedback。
